### ISSUE TITLE
Why not use support v4 Fragment in example?

### ISSUE THREAD

**Issue by ghost** [naver/navermap-android-api#1]
Why not use support v4 Fragment in example project?

(NMapFragment extended Fragment)

**Comment by suribada** [comment]
Thank you for your interest.
We have plan to modify our views into fragment-based-views.

**Comment by rrobbie1** [comment]
3개월전 studio 기반 gradle 환경으로 업데이트된후 이클립스에서 오래전부터 서비스중인 사람들을 위한 신규 nmap.jar를 공유할 계획은 없나요? 
예를 들어서 현재 제공되는 aar파일과 동일한 동작을 하는 jar파일 형태를 말합니다. 이는 aar파일을 참조하는 gradle 기반에서는 setScalingFactor(2.0f, true) 해당함수의 HD  기능이 정상 동작하지만 기존 nmap.jar 파일을 사용하는 이클립스 기반 서비스 운영중인곳에서는 setScalingFactor(2.0f, true) 해당 함수의 HD 기능이 동작하지 않아 에로사항이 많습니다.

**Comment by suribada** [comment]
We changed samples with support-v4 Fragment
