### ISSUE TITLE
3개월전 studio 기반 gradle 환경으로 업데이트된후 이클립스에서 오래전부터 서비스중인 사람들을 위한 신규 nmap.jar를 공유할 계획은 없나요? 

### ISSUE THREAD

**Issue by rrobbie1** [naver/navermap-android-api#2]
3개월전 studio 기반 gradle 환경으로 업데이트된후 이클립스에서 오래전부터 서비스중인 사람들을 위한 신규 nmap.jar를 공유할 계획은 없나요? 
예를 들어서 현재 제공되는 aar파일과 동일한 동작을 하는 jar파일 형태를 말합니다. 이는 aar파일을 참조하는 gradle 기반에서는 setScalingFactor(2.0f, true) 해당함수의 HD 기능이 정상 동작하지만 기존 nmap.jar 파일을 사용하는 이클립스 기반 서비스 운영중인곳에서는 setScalingFactor(2.0f, true) 해당 함수의 HD 기능이 동작하지 않아 에로사항이 많습니다.

**Comment by suribada** [comment]
개발자 카페에 답변을 했으나 다른 분들을 위해서도 공유합니다.
===========================================
수동으로 이클립스 라이브러러 프로젝트 만드는 방법은 다음과 같습니다.
(https://commonsware.com/blog/2014/07/03/consuming-aars-eclipse.html 참고)
1. NMapViewer(android)_v2.1.0_open.zip 압축 해제 
2. 압축 해제된 폴더 내에 app>libs>nmap.aar 파일 압축 해제
3. 빈 폴더 생성하여 NMapViewer(android)_v2.1.0_open 폴더 내의 AndroidManifest.xml, res/, asset/ 을 빈 폴더로 복사, classes.jar는 빈 폴더 내의 libs폴더 생성후 빈폴더/libs/ 로 복사
4. 이클립스에서 Existing Android Code Into Workspace이용하여 빈 폴더 프로젝트 import
5. 빈 폴더 프로젝트 오른쪽 단추->properties-> is Library 체크
6. 개발사 측 프로젝트에서 라이브러리 추가(빈 폴더 프로젝트)

내부적으로 이런 작업들을 스크립트로 만든 것들은 아래 내용들이 있습니다.
https://github.com/ksoichiro/gradle-eclipse-aar-plugin
https://gist.github.com/commonsguy/a3a534ea28ef8a82a213
