### ISSUE TITLE
Warning:com.nhn.android.maps.ScaleGestureDetector: can't find referenced method 'float sqrt(float)' in library class android.util.FloatMath

### ISSUE THREAD

**Issue by bicos** [naver/navermap-android-api#3]
현재 Warning:com.nhn.android.maps.ScaleGestureDetector: can't find referenced method 'float sqrt(float)' in library class android.util.FloatMath 라는 에러와 함께 빌드가 되지 않습니다.

확인해보니 float sqrt(float)' 메소드가 android sdk 22부터 deprecated 되었습니다. (23부터는 아예 삭제가 된 듯 합니다.) 확인해주시고 조속히 수정해주시길 바랍니다.

**Comment by suribada** [comment]
안녕하세요. 
최신버전 2.1.1에 해당 내용 적용하였습니다.
감사합니다.
