### ISSUE TITLE
naver map api 2.1.1 is not working

### ISSUE THREAD

**Issue by Acegugu** [naver/navermap-android-api#4]
![screenshot from 2016-03-02 09 42 09](https://cloud.githubusercontent.com/assets/1423080/13446964/149c87cc-e05b-11e5-93bd-6693c839d0a9.png)

naver map 2.1.1 is not working.

Issue enviroment is next
- compileSdkVersion : 23
- buildToolsVersion : 23.0.2
- minSdkVersion : 15
- targetSdkVersion : 23
- emulator : API 23(6.0.0) x64 (Genymotion) / Pure emulator API 23(6.0.0) x64 (AOSP)

But 2.1.0 is working in same enviroment.

**Comment by suribada** [comment]
2.1.0과 2.1.1이 방식이 달라진 것이 인증 방식입니다. 
새로운 버전을 사용하시려면 https://developers.naver.com/appinfo에서 새로운 ClientId를 발급받아서 기존 ApiKey 위치에 넣어야 합니다.

**Comment by Acegugu** [comment]
네 방금 확인했습니다 ㅎㅎ

2.1.1 라이브러리를 쓰려면 개발자 콘솔에서도 프로젝트 세팅을 다시하고 거기에서 얻은 ClientID로 프로젝트에 세팅을 해둬야 하더군요.

답변 감사합니다.
