### ISSUE TITLE
최신 라이브러리 (2.1.1) 빌드 이슈

### ISSUE THREAD

**Issue by bicos** [naver/navermap-android-api#6]
Uncaught translation error: com.android.dx.cf.code.SimException: com.android.dx.rop.cst.CstInterfaceMethodRef cannot be cast to com.android.dx.rop.cst.CstMethodRef

이런 메세지가 뜨면서 릴리즈 빌드가 불가합니다.. 해당 사항 확인 부탁드립니다.

참고로 2.1.0은 정상적으로 빌드되는것을 확인하였습니다.

**Comment by suribada** [comment]
이 문제는 play-services 버전 관련 문제입니다. 
https://code.google.com/p/android/issues/detail?id=187483

play-service 버전을 8.3 또는 그 이상을 사용해보시기 바랍니다.
